# charts/bedrock-chat/values.yaml

replicaCount: 1

image:
  repository: <YOUR_ACCOUNT>.dkr.ecr.us-east-2.amazonaws.com/llm-chat
  tag: "0.1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

env:
  AWS_REGION: "us-east-1"
  MODEL_ID: "anthropic.claude-3-haiku-20240307-v1:0"
  RAG_S3_BUCKET: ""
  RAG_S3_PREFIX: ""
  RAG_ADMIN_TOKEN: ""

persistence:
  enabled: true
  size: 1Gi
  storageClassName: ""

serviceAccount:
  create: false
  name: bedrock-sa

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi